"""Concise six-domain narration and visual plan for the DQIP demonstration."""

from __future__ import annotations

from scene_manager import Scene


DEMO_SCENES = [
    Scene("DQIP Cross-Domain Quality Intelligence", "Welcome to the Digital Quality Intelligence Platform, or DQIP. This application converts test, inspection, operational, and monitoring data into structured quality intelligence. In the next six minutes, we will demonstrate how one reusable analytics core supports six distinct quality domains while preserving the correct terminology, limits, risk logic, and reporting context for each application.", "opening"),
    Scene("One Core—Six Quality Domains", "The workspace provides dedicated profiles for Construction Quality, Manufacturing, Laboratory Quality Assurance, Healthcare, Pharmaceuticals, and Environmental Monitoring. Selecting a profile changes the model input schema, quality characteristic, acceptance logic, dashboard language, standards references, reasons, corrective measures, and report title. Concrete evaluation is the validated demonstration workflow. The remaining profiles are illustrative models requiring domain validation before operational use.", "cross_domain"),
    Scene("Construction Quality—Data and Compliance", "Construction Quality begins with concrete cube-strength results imported from Microsoft Excel. The application validates the workbook, isolates completed twenty-eight-day tests, recognises the concrete grade, and applies grade-aware acceptance rules. Engineers can review measured strength, specified strength, project structure, mix, supplier, and test history before evaluating compliance.", "construction_profile"),
    Scene("Construction Quality—Capability and Risk", "The construction dashboard combines average strength, compliance, coefficient of variation, sigma performance, C P, C P K, P P K, yield, and defects per million opportunities. Strength trends, control charts, distribution analysis, supplier comparisons, abnormality alerts, and risk interpretation identify variation before it becomes a quality failure. The platform also recommends practical investigation and corrective measures.", "construction_intelligence"),
    Scene("Manufacturing—Dimensional Intelligence", "The Manufacturing profile evaluates dimensional inspection data. It compares measured diameter with nominal dimensions and approved lower and upper specification limits. The dashboard calculates yield, flagged components, process capability, sigma level, and variation while comparing machines, production lines, shifts, and operators. Trend signals can indicate tool wear, machine drift, calibration problems, or unstable process settings.", "manufacturing"),
    Scene("Manufacturing—Corrective Action", "Manufacturing risk intelligence translates statistical signals into engineering action. Out-of-tolerance parts can trigger containment, gauge verification, tool inspection, parameter correction, and follow-up capability studies. The report retains the manufacturing terminology and measured characteristic, rather than presenting concrete-related labels or recommendations.", "manufacturing_actions"),
    Scene("Laboratory QA—Analytical Performance", "Laboratory Quality Assurance evaluates analytical results against method-specific limits. The sample workflow monitors p H results by test date, batch, analyst, and instrument. It highlights exceptions, estimates repeatability and capability, and identifies instrument drift, calibration concerns, reference-material issues, or inconsistent sample preparation. Standards references support method governance without inventing a universal acceptance range.", "laboratory"),
    Scene("Laboratory QA—Evidence and Review", "The laboratory dashboard connects result trends, instrument comparisons, exceptions, risk classification, possible reasons, and corrective action. Recommended responses include reviewing calibration status, control samples, reagents, environmental conditions, analyst technique, and method validity. Evaluated data and the domain-labelled PDF provide traceable evidence for technical review.", "laboratory_actions"),
    Scene("Healthcare—Operational Quality", "The Healthcare profile uses de-identified operational indicators and is not intended for clinical diagnosis. In this demonstration, waiting time is evaluated against an approved service target. The dashboard compares departments and shifts, measures service yield and variation, detects delays, and suggests operational investigation involving demand, staffing, scheduling, hand-offs, and process bottlenecks.", "healthcare"),
    Scene("Pharmaceuticals—Batch Quality", "The Pharmaceuticals profile evaluates batch and product quality characteristics such as assay and dissolution against approved specifications. It identifies failed or marginal results, compares products and batches, calculates capability where appropriate, and highlights possible laboratory, material, process, or stability-related causes. Any production use requires validated methods, approved specifications, data-integrity controls, and the applicable regulatory framework.", "pharmaceuticals"),
    Scene("Environmental Monitoring—Parameter Compliance", "Environmental Monitoring evaluates measurements within their site and parameter context. The demonstration reviews p H, turbidity, and chlorine results by sampling date and location. It detects threshold exceedances, location trends, process shifts, and incomplete records. Corrective guidance can include resampling, instrument checks, treatment review, source investigation, and escalation under the authorised monitoring programme.", "environmental"),
    Scene("Common Intelligence—Domain-Specific Meaning", "Across every profile, DQIP uses a common statistical foundation for trend analysis, variation, capability, sigma performance, yield, defects, abnormality detection, and risk classification. What changes is the quality meaning. Units, labels, limits, grouping factors, standards references, likely causes, and corrective actions remain specific to the selected domain.", "common_intelligence"),
    Scene("Reports and Decision Support", "Each domain provides evaluated data export, a professional P D F report, and a print-ready executive dashboard. Reports display the correct domain name, quality characteristic, calculated evidence, interpretation, risk, abnormalities, opportunities, corrective measures, and reference framework. This supports engineering presentations, audits, management review, client communication, and research demonstrations.", "reports"),
    Scene("Transparent Validation Boundaries", "DQIP is decision-support software, not a replacement for engineering, laboratory, clinical, pharmaceutical, or environmental expertise. Concrete Quality is the validated profile in this prototype. Every other profile is visibly marked as illustrative. Before production use, organisations must validate the input schema, measurement method, acceptance limits, calculations, standards applicability, and recommended actions for their process and jurisdiction.", "validation"),
    Scene("From Data to Defensible Decisions", "DQIP demonstrates how one configurable quality-intelligence architecture can serve multiple technical domains without losing domain identity. By connecting data, statistical evaluation, risk reasoning, corrective action, visualisation, and reporting, the platform helps specialists make faster, clearer, and more defensible quality decisions. Thank you for watching, and please share which domain should be developed and validated next.", "closing"),
]
